### ISSUE TITLE
Another C# Port

### ISSUE THREAD

**Issue by adrianseeley** [sveinn-steinarsson/flot-downsample#13]
https://gist.github.com/adrianseeley/264417d295ccd006e7fd

test on sin(x / 2) 100 points, normalized, downsampled to 10 points

http://i.imgur.com/UwhvV45.png

**Comment by sveinn-steinarsson** [comment]
Very nice. Thank you.
It should be noted that LTTB is not good at downsampling data derived from mathematical functions like sin.

**Comment by adrianseeley** [comment]
Thanks for the heads up! 

It's been working pretty good for me today! I'm using it for offline time series clustering, as a preprocessing step, which then heads into a KNN algorithm.

Graphing the KN-neighbourhood then reveals some interesting patterns when laid out properly, for example, here is TAN(X) / 2:

http://imgur.com/ceGPQgx

Thanks Sveinn!

**Comment by sveinn-steinarsson** [comment]
Very cool!
