### ISSUE TITLE
Question: Performance metrics

### ISSUE THREAD

**Issue by adriangibbons** [sveinn-steinarsson/flot-downsample#18]
Hi, this looks interesting. How you already got any metrics to show Flot's performance is enhanced using this plugin? It's pretty fast already.

Or are there other reasons for using it? E.g. better aesthetics or other?

I'd look into it more but am travelling with work, plus you might have this information already.

Thanks, Adrian

**Comment by qking** [comment]
We use the downsample plug-in and it makes a big difference when zooming out with a large dataset. We can display up to 1E7 samples with acceptable zoom lag (˜1s when returning to the full data set). Without downsampling, it’s 5 times slower.

Best regards,
Quentin

Quentin King
CERN  TE-EPC-CCS
Tel: +41 22 767 8473

**Comment by adriangibbons** [comment]
Hi Quentin, thanks for sharing your experience and good example of a practical application.

Out of interest, by zooming - are you using a Flot plugin for this functionality or re-drawing the chart with a subset of the data manually?

Cheers

**Comment by qking** [comment]
Hi Adrian,

We use these FLOT plugins:

    <script src="assets/vendor/flot-v0.8.3/jquery.flot.resize.js"></script>
    <script src="assets/vendor/flot-v0.8.3/jquery.flot.selection.js"></script>
    <script src="assets/vendor/flot-v0.8.3/jquery.flot.tooltip.js"></script>
    <script src="assets/vendor/flot-v0.8.3/jquery.flot.downsample.js"></script>

The selection plugin gives us the ability to do a zoom stack.

Best regards,
Quentin

Quentin King
CERN  TE-EPC-CCS
Tel: +41 22 767 8473
