### ISSUE TITLE
Chart.js port/wrapper

### ISSUE THREAD

**Issue by AlbinoDrought** [sveinn-steinarsson/flot-downsample#20]
Hey,

I've converted this plugin to work with Chart.js: https://github.com/AlbinoDrought/chartjs-plugin-downsample

Was looking for something like this but couldn't find one, so I ended up cobbling some stuff together.

It's available on npm as `chartjs-plugin-downsample`

Thanks for the great implementation!

**Comment by sveinn-steinarsson** [comment]
Thank you. Well done.
