### ISSUE TITLE
Small Optimization

### ISSUE THREAD

**Issue by erlendrobaye** [sveinn-steinarsson/flot-downsample#25]
A small suggestion: the calculation of the triangular area could be changed to a calculation of a rectangular area and thus get rid of the *.5 ( or division by 2), since the size of the area is only used to compare...

**Comment by i813812** [comment]
agree - addionally you could move the calculation (point_a_x - avg_x) and (avg_y - point_a_y) before the loop. The coding should then look like:

      max_area = area = -1;

      let ax_minus_avgx = point_a_x - avg_x;  
      let avgy_minus_ay = avg_y - point_a_y;

      for (; range_offs < range_to; range_offs++) {
        // Calculate triangle area over three buckets
        area = Math.abs((ax_minus_avgx) * (data[range_offs][1] - point_a_y) -
          (point_a_x - data[range_offs][0]) * (avgy_minus_ay));
        if (area > max_area) {
          max_area = area;
          max_area_point = data[range_offs];
          next_a = range_offs; // Next a is this b
        }
      }

**Comment by sveinn-steinarsson** [comment]
This is an interesting idea but I want to keep the current algorithm as is. If you fork it and preferably add some tests I can maybe add it under https://github.com/sveinn-steinarsson/flot-downsample#the-algorithm-lttb-adapted-for-other-programming-languages-or-frameworks
